version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:4.4-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always