version: "3"

services:
  image: mongo:4.4-bionic
  container_name: mongo
  restart: always
  environment:
    MONGO_INITDB_ROOT_USERNAME: admin
    MONGO_INITDB_ROOT_PASSWORD: admin
    MONGO_INITDB_DATABASE: ecommerce
