@server = http://localhost:3002
@endPoint = api/sizes
@sizeId = 662e4ee36a55d308d5d0d1cc

### POST /
POST {{ server }}/{{ endPoint }} HTTP/1.1
Content-Type: application/json

{
  "name": "Fake size"
}

### PUT /:id
PUT {{ server }}/{{ endPoint }}/{{ sizeId }} HTTP/1.1
Content-Type: application/json

{
  "name": "Fake new size"
}

### DELETE /:id
DELETE  {{ server }}/{{ endPoint }}/{{ sizeId }} HTTP/1.1

### GET /:id
GET  {{ server }}/{{ endPoint }}/{{ sizeId }} HTTP/1.1

### GET /
GET  {{ server }}/{{ endPoint }} HTTP/1.1