export { default as Dashboard } from './dashboard'
export { default as Categories } from './categories'
export { default as Products } from './products'
export { default as Orders } from './orders'
export { default as Users } from './users'
