@server=http://localhost:3001
@endPoint=auth

### POST /create
POST {{ server }}/{{ endPoint }}/create HTTP/1.1
Content-Type: application/json

{
  "username": "fakefirst",
  "email": "fakefirst@email.com",
  "password": "password",
  "image": "https://lh3.googleusercontent.com/a/AAcHTtcRLD0NaIOz4aNsYR811qJxXWMFExFwo3_zqL3cDg=s360-c-no",
  "country": "Brazil",
  "phone": "123456789",
  "description": "Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident",
  "isSeller": true
}

### POST /login
POST {{ server }}/{{ endPoint }}/login HTTP/1.1
Content-Type: application/json

{
  "username": "fakefirst",
  "password": "password"
}

### POST /logout
POST {{ server }}/{{ endPoint }}/logout HTTP/1.1
